Validate all known pdsc files against new schema.

diff --git a/.github/workflows/schema.yaml b/.github/workflows/schema.yaml
--- a/.github/workflows/schema.yaml
+++ b/.github/workflows/schema.yaml
@@ -7,6 +7,8 @@ on:
     paths:
       - '.github/workflows/schema.yaml'
       - 'schema/**'
+  schedule:
+    - cron: '0 6 * * *'
 jobs:
   pack:
     name: Validate pack schema
@@ -18,14 +20,27 @@ jobs:
         run: |
           sudo apt-get update
           sudo apt-get install --no-install-recommends -y libxml2-utils
+          sudo pip install progress
+      - name: Cache Keil index pdsc files
+        uses: actions/cache@v2
+        id: cache
+        with:
+          path: .Web
+          key: keilindex
+      - name: Fill cache
+        if: ${{ steps.cache.outputs.cache-hit != 'true' || github.event_name == 'schedule' || github.event_name == 'workflow_dispatch' }}
+        run: python3 .github/download-pack-index.py -f
       - name: Run xmllint against XMLSchema.xsd
         run: |
           wget https://www.w3.org/2012/04/XMLSchema.xsd
           xmllint --noout --schema XMLSchema.xsd schema/pack.xsd
-      - name: Run xmllint against ARM.CMSIS.pdsc
+      - name: Run xmllint against Keil index
         run: |
-          wget http://www.keil.com/pack/ARM.CMSIS.pdsc
-          xmllint --noout --schema schema/pack.xsd ARM.CMSIS.pdsc
+          for f in $(find .Web -name *.pdsc); do
+            if ! xmllint --noout --schema schema/pack.xsd $f; then
+              echo "::error file=schema/pack.xsd::Schema validation failed for $(basename $f)"
+            fi
+          done
 
   index:
     name: Validate index schema
